import Database from "better-sqlite3";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = process.cwd();
const dbPath = process.env.HUERTO_DB_PATH ?? path.join(root, "data", "huerto_regenerativo.sqlite");
const outDir = path.join(root, "data", "derived");
const outPath = path.join(outDir, "crop_evidence_profiles.json");

const db = new Database(dbPath, { readonly: true, fileMustExist: true });
db.pragma("query_only = ON");

const CURATED_GARDEN_CROPS = new Set([
  "allium ampeloprasum",
  "allium sativum",
  "allium spp",
  "anethum graveolens",
  "apium graveolens",
  "asparagus offininalis",
  "beta vulgaris",
  "brassica oleracea",
  "brassica rapa",
  "capsicum annum",
  "cichorium intybus",
  "cicer arietinum",
  "citrullus lanatus",
  "coriandrum sativum",
  "cucumis melo",
  "cucumis sativus",
  "cucurbita spp",
  "daucus carota",
  "eruca vesicaria subsp sativa",
  "fragaria x ananassa",
  "lactuca sativa",
  "lens culinaris",
  "lycopersicon esculentum",
  "ocimum basilicum",
  "petroselinum crispum",
  "phaseolus spp",
  "phaseolus vulgaris",
  "pisum spp",
  "raphanus sativus",
  "solanum melongena",
  "solanum tuberosum",
  "spinacia oleracea",
  "vicia faba",
  "zea mais"
]);

const CURATED_EXTRA_CROPS = [
  {
    scientificName: "Phaseolus vulgaris",
    commonName: "Poroto seco o granado",
    family: "Fabaceae",
    genus: "Phaseolus",
    species: "Phaseolus vulgaris"
  },
  {
    scientificName: "Lens culinaris",
    commonName: "Lenteja",
    family: "Fabaceae",
    genus: "Lens",
    species: "Lens culinaris"
  },
  {
    scientificName: "Cicer arietinum",
    commonName: "Garbanzo",
    family: "Fabaceae",
    genus: "Cicer",
    species: "Cicer arietinum"
  }
];

const crops = mergeCuratedCatalogRows(
  db
    .prepare(
      `
    SELECT
      TRIM(REPLACE(REPLACE(crop_latin_name, 'V-', ''), 'F-', '')) AS scientificName,
      COALESCE(MIN(crop_common_name), crop_latin_name) AS commonName,
      COALESCE(family, 'Familia no clasificada') AS family,
      MIN(genus) AS genus,
      MIN(species) AS species
    FROM crop_catalog_seed
    WHERE crop_latin_name IS NOT NULL
      AND lower(crop_latin_name) NOT LIKE '%cannabis%'
    GROUP BY TRIM(REPLACE(REPLACE(crop_latin_name, 'V-', ''), 'F-', '')), COALESCE(family, 'Familia no clasificada')
    ORDER BY commonName
  `
    )
    .all()
).filter((crop) => isCuratedGardenCrop(crop.scientificName));

const yieldStmt = db.prepare(
  `
  SELECT item, AVG(CAST(value AS REAL)) / 10000 AS yieldKgM2, COUNT(*) AS observations
  FROM faostat_chile_crop_livestock_production
  WHERE element = 'Yield'
    AND unit = 'kg/ha'
    AND item = ?
    AND CAST(year AS INTEGER) BETWEEN 2020 AND 2024
    AND value IS NOT NULL
  GROUP BY item
`
);

const agentStmt = db.prepare(
  `
  SELECT agent_type AS type, agent_name AS name, host_status AS hostStatus, disease_reduction AS diseaseReduction
  FROM best4soil_crop_agent_risk
  WHERE TRIM(REPLACE(REPLACE(crop_latin_name, 'V-', ''), 'F-', '')) = ?
    AND agent_name IS NOT NULL
  ORDER BY agent_name
`
);

const nutritionStmt = db.prepare(
  `
  SELECT fdc_id AS fdcId, description, data_type AS dataType, COUNT(*) AS nutrientCount
  FROM fdc_core_food_nutrients
  WHERE lower(description) LIKE ?
  GROUP BY fdc_id, description, data_type
  ORDER BY
    CASE
      WHEN lower(description) LIKE '%raw%' THEN 0
      WHEN lower(description) LIKE '%fresh%' THEN 1
      WHEN lower(description) LIKE '%cooked%' THEN 2
      ELSE 3
    END,
    nutrientCount DESC,
    LENGTH(description)
  LIMIT 1
`
);

const profiles = crops.map((crop) => {
  const faostatItem = faostatItemFor(crop.scientificName, crop.commonName ?? "");
  const yieldProfile = faostatItem ? yieldStmt.get(faostatItem) : null;
  const curatedNutrition = curatedNutritionFor(crop.scientificName, crop.commonName ?? "");
  const aliases = curatedNutrition ? [] : buildAliases(crop.commonName ?? crop.scientificName, crop.scientificName);
  const nutritionMatch =
    curatedNutrition?.foodCrop === false
      ? null
      : curatedNutrition
        ? nutritionStmt.get(`%${curatedNutrition.description.toLowerCase()}%`)
        : aliases.map((alias) => nutritionStmt.get(`%${alias}%`)).find(Boolean) ?? null;
  const agents = agentStmt.all(crop.scientificName);

  return {
    scientificName: crop.scientificName,
    commonName: crop.commonName,
    family: crop.family,
    genus: crop.genus,
    species: crop.species,
    nutritionMatch: nutritionMatch
      ? {
          quality: curatedNutrition?.level ?? "candidate",
          source:
            curatedNutrition?.source ??
            "USDA FoodData Central local; candidate generated by alias search",
          matchingMethod: curatedNutrition ? "curated-fdc-description" : "alias-search",
          matchingNotes: curatedNutrition?.label,
          ...nutritionMatch
        }
      : {
          quality: curatedNutrition?.foodCrop === false ? "not-human-food-crop" : "missing",
          source:
            curatedNutrition?.source ??
            "USDA FoodData Central local; FAO/INFOODS food matching criteria",
          matchingNotes: curatedNutrition?.label
        },
    yieldProfile: yieldProfile
      ? {
          level: "observed",
          source: "FAOSTAT Chile local",
          years: "2020-2024",
          ...yieldProfile
        }
      : {
          level: "missing",
          source: "FAOSTAT Chile local",
          item: faostatItem
        },
    rotationProfile: {
      source: "Best4Soil local",
      agentCount: agents.length,
      agents: agents.slice(0, 24)
    }
  };
});

mkdirSync(outDir, { recursive: true });
writeFileSync(
  outPath,
  `${JSON.stringify(
    {
      generatedAt: new Date().toISOString(),
      method: "Derived evidence profile seed from local SQLite tables; scoring still hydrates live records in lib/db.ts.",
      profiles
    },
    null,
    2
  )}\n`
);

console.log(`Wrote ${profiles.length} crop evidence profiles to ${outPath}`);
db.close();

function faostatItemFor(scientificName, commonName) {
  const text = `${scientificName} ${commonName}`.toLowerCase();
  const exact = [
    ["lycopersicon", "Tomatoes"],
    ["solanum lycopersicum", "Tomatoes"],
    ["solanum tuberosum", "Potatoes"],
    ["allium cepa", "Onions and shallots, dry (excluding dehydrated)"],
    ["allium spp", "Onions and shallots, dry (excluding dehydrated)"],
    ["daucus carota", "Carrots and turnips"],
    ["raphanus", "Carrots and turnips"],
    ["capsicum", "Chillies and peppers, green (Capsicum spp. and Pimenta spp.)"],
    ["brassica oleracea", "Cabbages"],
    ["cucurbita", "Pumpkins, squash and gourds"],
    ["cucumis sativus", "Cucumbers and gherkins"],
    ["lactuca", "Lettuce and chicory"],
    ["vicia faba", "Broad beans and horse beans, green"],
    ["pisum", "Peas, green"],
    ["phaseolus vulgaris", "Beans, dry"],
    ["phaseolus", "Other beans, green"],
    ["lens culinaris", "Lentils, dry"],
    ["cicer arietinum", "Chick peas, dry"],
    ["spinacia", "Spinach"],
    ["fragaria", "Strawberries"],
    ["zea", "Green corn (maize)"]
  ];
  return exact.find(([key]) => text.includes(key))?.[1] ?? null;
}

function buildAliases(commonName, scientificName) {
  const stopAliases = new Set([
    "incl",
    "leafy",
    "black",
    "white",
    "green",
    "sweet",
    "italian",
    "japanese",
    "perennial",
    "red",
    "sp",
    "spp",
    "subsp",
    "sativa",
    "sativum"
  ]);
  const raw = [commonName, scientificName.split(" ")[0], scientificName.split(" ")[1] ?? ""]
    .map((value) => value.toLowerCase().replace(/[^a-z ]/g, " ").trim())
    .filter((value) => value.length > 3 && !stopAliases.has(value));
  const parts = raw
    .flatMap((value) => value.split(/\s+|\/|,/))
    .filter((value) => value.length > 3 && !stopAliases.has(value));
  return Array.from(new Set([...raw, ...parts])).slice(0, 8);
}

function mergeCuratedCatalogRows(rows) {
  const byId = new Map();
  for (const row of [...rows, ...CURATED_EXTRA_CROPS]) {
    const key = slugKey(row.scientificName);
    if (!byId.has(key) || CURATED_EXTRA_CROPS.some((crop) => slugKey(crop.scientificName) === key)) {
      byId.set(key, row);
    }
  }
  return Array.from(byId.values());
}

function isCuratedGardenCrop(scientificName) {
  return CURATED_GARDEN_CROPS.has(normalizeCatalogText(scientificName));
}

function normalizeCatalogText(value) {
  return value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/^[vf]-/, "")
    .replace(/[^a-z0-9 ]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

function slugKey(value) {
  return normalizeCatalogText(value).replace(/[^a-z0-9]+/g, "-");
}

function curatedNutritionProfiles() {
  return [
  food("allium ampeloprasum", "Leeks, (bulb and lower leaf-portion), raw", "Leek crudo; match taxonomico curado"),
  food("allium sativum", "Garlic, raw", "Ajo crudo; match taxonomico curado"),
  food("allium spp", "Onions, raw", "Cebolla cruda; proxy de especie Allium horticola", "proxy"),
  food("anethum graveolens", "Dill weed, fresh", "Eneldo fresco; corrige nombre comun ambiguo del catalogo"),
  food("apium graveolens", "Celery, raw", "Apio crudo; match taxonomico curado"),
  food("asparagus offininalis", "Asparagus, raw", "Esparrago crudo; match por genero con correccion ortografica"),
  food("avena sativa", "Cereals, oats, regular and quick, not fortified, dry", "Avena seca no fortificada; proxy de grano entero disponible en FDC"),
  food("avena strigosa", "Cereals, oats, regular and quick, not fortified, dry", "Avena negra; proxy por Avena sativa disponible en FDC"),
  food("beta vulgaris", "Beets, raw", "Betarraga cruda; match de especie horticola"),
  food("brassica napus", "Spices, mustard seed, ground", "Semilla de mostaza molida; proxy para semilla oleaginosa Brassica", "proxy"),
  food("brassica oleracea", "Cabbage, raw", "Repollo crudo; representante para Brassica oleracea mixta"),
  food("brassica rapa", "Turnips, raw", "Nabo crudo; match taxonomico curado"),
  food("brassica spp", "Turnip greens, raw", "Hojas de nabo crudas; proxy para Brassica de hoja/abono verde", "proxy"),
  food("capsicum annum", "Peppers, sweet, red, raw", "Pimenton rojo crudo; corrige alias generico sweet"),
  food("cichorium intybus", "Chicory greens, raw", "Hojas de achicoria crudas; match taxonomico curado"),
  food("citrullus lanatus", "Watermelon, raw", "Sandia cruda; corrige ortografia Watermelone"),
  food("coriandrum sativum", "Coriander (cilantro) leaves, raw", "Cilantro fresco crudo; match coriander/cilantro"),
  food("cucumis melo", "Melons, cantaloupe, raw", "Melon cantalupo crudo; proxy para Cucumis melo", "proxy"),
  food("cucumis sativus", "Cucumber, peeled, raw", "Pepino crudo; match taxonomico curado"),
  food("cucurbita spp", "Pumpkin, raw", "Zapallo/calabaza crudo; proxy de genero Cucurbita", "proxy"),
  food("daucus carota", "Carrots, raw", "Zanahoria cruda; match taxonomico curado"),
  food("eruca vesicaria", "Arugula, raw", "Rucula/arugula cruda; agrega especie sin match previo"),
  food("fagopyrum esculentum", "Buckwheat", "Trigo sarraceno; match de pseudocereal disponible en FDC"),
  food("fragaria x ananassa", "Strawberries, raw", "Frutilla cruda; corrige match a topping de frutilla"),
  food("cicer arietinum", "Chickpeas (garbanzo beans, bengal gram), mature seeds, raw", "Garbanzo maduro crudo; leguminosa alimentaria agregada al catalogo curado"),
  food("glycine max", "Soybeans, green, raw", "Soya verde cruda; match taxonomico curado"),
  food("guizotia abyssinica", "Seeds, safflower seed kernels, dried", "Proxy por semilla de cartamo ante ausencia de ramtil/niger en FDC local", "proxy"),
  food("helianthus spp", "Seeds, sunflower seed kernels, dried", "Semilla de maravilla cruda; proxy de genero Helianthus", "proxy"),
  food("hordeum vulgare", "Barley, pearled, raw", "Cebada perlada cruda; match de cereal disponible en FDC"),
  food("lactuca sativa", "Lettuce, cos or romaine, raw", "Lechuga cruda; match taxonomico curado"),
  food("lathyrus sativus", "Peas, green, raw", "Arveja; proxy para almorta/chickling pea sin perfil FDC directo", "proxy"),
  food("lens culinaris", "Lentils, raw", "Lenteja cruda; leguminosa alimentaria agregada al catalogo curado"),
  food("linum usitatissiumum", "Seeds, flaxseed", "Linaza/flaxseed; agrega especie sin match previo"),
  food("lupinus spp", "Lupins, mature seeds, raw", "Lupino maduro crudo; proxy por genero Lupinus", "proxy"),
  food("lycopersicon esculentum", "Tomatoes, red, ripe, raw, year round average", "Tomate crudo; match taxonomico curado"),
  food("medigaco sativa", "Alfalfa seeds, sprouted, raw", "Brotes de alfalfa crudos; proxy comestible de alfalfa", "proxy"),
  food("ocimum basilicum", "Basil, fresh", "Albahaca fresca; match taxonomico curado"),
  food("oryza sativa", "Rice, brown, long-grain, raw", "Arroz integral crudo; evita match a arroz silvestre"),
  food("pastinaca sativa", "Parsnips, raw", "Chirivia cruda; match taxonomico curado"),
  food("petroselinum crispum", "Parsley, fresh", "Perejil fresco; match taxonomico curado"),
  food("phaseolus spp", "Beans, snap, green, raw", "Poroto verde crudo; proxy horticola de Phaseolus", "proxy"),
  food("phaseolus vulgaris", "Beans, pinto, mature seeds, raw", "Poroto maduro crudo; proxy por poroto pinto USDA para poroto seco/granado", "proxy"),
  food("pisum spp", "Peas, green, raw", "Arveja verde; proxy de Pisum disponible en FDC", "proxy"),
  food("raphanus sativus", "Radishes, raw", "Rabano crudo; match taxonomico curado"),
  food("rheum rhabarbarum", "Rhubarb, raw", "Ruibarbo crudo; match taxonomico curado"),
  food("scorzonera hispanica", "Salsify, (vegetable oyster), raw", "Salsifi negro; corrige falso match con berries"),
  food("secale cereale", "Rye grain", "Grano de centeno; corrige falso match con chicken fryers"),
  food("sinapis alba", "Spices, mustard seed, ground", "Semilla de mostaza molida; agrega mostaza blanca"),
  food("solanum melongena", "Eggplant, raw", "Berenjena cruda; match taxonomico curado"),
  food("solanum tuberosum", "Potatoes, flesh and skin, raw", "Papa cruda; match taxonomico curado"),
  food("sorghum spp", "Sorghum grain", "Sorgo grano entero; proxy por genero Sorghum", "proxy"),
  food("spinacia oleracea", "Spinach, raw", "Espinaca cruda; match taxonomico curado"),
  food("triticum aestivum", "Wheat, hard red spring", "Trigo duro rojo de primavera; proxy de grano de trigo disponible en FDC", "proxy"),
  food("triticosecale", "Triticale", "Triticale; match de cereal disponible en FDC"),
  food("valerianella sp", "Cornsalad, raw", "Canonigo/cornsalad crudo; corrige falso match por sp"),
  food("vicia faba", "Broadbeans, immature seeds, raw", "Haba verde cruda; match taxonomico curado"),
  food("vicia sp", "Beans, fava, in pod, raw", "Vicia; proxy por haba verde para especie de Vicia sin perfil FDC directo", "proxy"),
  food("zea mais", "Corn, sweet, yellow, raw", "Maiz dulce amarillo crudo; corrige falso match por Zea"),
  nonFood("lolium multiflorum", "Cultivo forrajero/cobertura: sin perfil alimentario humano confiable"),
  nonFood("lolium perenne", "Cultivo forrajero/cobertura: sin perfil alimentario humano confiable"),
  nonFood("nicotiana tabacum", "No se modela como alimento por uso no alimentario y riesgo sanitario"),
  nonFood("phacelia sp", "Cultivo de servicio para polinizadores/cobertura: sin perfil alimentario humano confiable"),
  nonFood("tagetes sp", "Cultivo de servicio/ornamental: sin perfil alimentario humano confiable"),
  nonFood("trifolium alexandrinum", "Trebol forrajero/cobertura: sin perfil alimentario humano confiable"),
  nonFood("trifolium incarnatum", "Trebol forrajero/cobertura: sin perfil alimentario humano confiable"),
  nonFood("trifolium pratense", "Trebol forrajero/cobertura: sin perfil alimentario humano confiable"),
  nonFood("trifolium repens", "Trebol forrajero/cobertura: sin perfil alimentario humano confiable"),
  nonFood("trifolium resupinatum", "Trebol forrajero/cobertura: sin perfil alimentario humano confiable"),
  nonFood("trifolium spp", "Trebol forrajero/cobertura: sin perfil alimentario humano confiable")
  ];
}

function curatedNutritionFor(scientificName, commonName) {
  const normalized = `${scientificName} ${commonName}`.toLowerCase().replace(/×/g, "x").replace(/[^a-z0-9 ]/g, " ");
  return curatedNutritionProfiles().find((profile) => profile.match.some((item) => normalized.includes(item)));
}

function food(match, description, label, level = "observed") {
  return {
    description,
    level,
    label,
    source:
      "USDA FoodData Central local; criterio de match FAO/INFOODS; contraste nacional Tabla de Composicion Quimica de Alimentos Chilenos",
    match: [match.toLowerCase().replace(/[^a-z0-9 ]/g, " ").trim()]
  };
}

function nonFood(match, label) {
  return {
    foodCrop: false,
    label,
    source: "Revision curada FDC/FAO INFOODS/Tabla chilena; se conserva valor nutricional humano como ausente",
    match: [match.toLowerCase().replace(/[^a-z0-9 ]/g, " ").trim()]
  };
}
